### ISSUE TITLE
mypy native support for assert_type

### ISSUE THREAD

**Issue by Rogdham** [thejcannon/typing-asserts#5]
Hello,

It seems that [mypy now has support for `assert_type`](https://mypy.readthedocs.io/en/stable/error_code_list.html#check-types-in-assert-type-assert-type) ([related PR](https://github.com/python/mypy/pull/12584)).

_Btw, [`assert_type` will be in stdlib](https://docs.python.org/3.11/library/typing.html#typing.assert_type) starting from Python 3.11 (although not doing anything by itself)._

So I'm curious: does your library provide any added features, or was it just a temporary way to have an `assert_type` function until the implementation in mypy?

**Comment by thejcannon** [comment]
The latter, for sure "temporary way to have an assert_type function until the implementation in mypy"

I had some code which was very complex in terms of generic typing and needed a way to make sure changes to the codebase didn't change the resulting typing, and at the time `mypy` didn't support it (and I couldn't use the other type-checking libraries).

I'll be very happy to archive this library/repo when `assert_type` is something I'll be able to use in my code :sweat_smile:

**Comment by Rogdham** [comment]
Alright, noted, thank you for the answer!

Right now, something like the following can be used:

```python
if TYPE_CHECKING:
    from typing_extensions import assert_type
else:
    def assert_type(val, _):
        return val
```
